# frozen_string_literal: true

namespace :active_admin do
  desc "Concatenate ActiveAdmin JavaScript for Propshaft"
  task bundle_js: :environment do
    require "pathname"

    aa = Pathname.new(Gem.loaded_specs["activeadmin"].full_gem_path)
    jq = Pathname.new(Gem.loaded_specs["jquery-rails"].full_gem_path)
    out = Rails.root.join("app/assets/builds/active_admin.js")

    files = [
      jq.join("vendor/assets/javascripts/jquery3.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/version.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/data.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/disable-selection.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/focusable.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/form-reset-mixin.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/keycode.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/labels.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/plugin.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/position.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/scroll-parent.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/tabbable.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/unique-id.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/widget.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/widgets/mouse.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/widgets/datepicker.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/widgets/button.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/widgets/dialog.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/widgets/resizable.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/widgets/sortable.js"),
      aa.join("vendor/assets/javascripts/jquery-ui/widgets/tabs.js"),
      jq.join("vendor/assets/javascripts/jquery_ujs.js"),
      aa.join("app/assets/javascripts/active_admin/base.js")
    ]

    FileUtils.mkdir_p(out.dirname)
    File.open(out, "w") do |f|
      f.puts "/* Generated by rake active_admin:bundle_js — do not edit */"
      files.each do |path|
        raise "Missing #{path}" unless path.exist?
        body = path.read
        # Drop sprockets directives from base.js; keep the rest
        body = body.lines.reject { |l| l.start_with?("//= ") }.join
        f.puts "\n/* ===== #{path.basename} ===== */\n"
        f.write(body)
        f.puts ";"
      end
    end

    puts "Wrote #{out} (#{out.size} bytes)"
  end
end
